on: [push, pull_request]
name: split example
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Split version code
        uses: xom9ikk/split@v1
        id: split
        with:
          string: 2.17.3
          separator: .
          limit: -1

      - name: Some other action
        with:
          major: ${{ steps.split.outputs._0 }}
          minor: ${{ steps.split.outputs._1 }}
          patch: ${{ steps.split.outputs._2 }}
