on: [push, pull_request]
name: split example
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Split version code
        uses: action
#         id: split
#         with:
#           string: 'Alpha-13'
#           split-by: '-'
      - run: | 
          echo ${New variable}
